<?php

/**
* Implements hook_ckeditor_settings_alter().
*/
function eige_ckeditor_ckeditor_settings_alter(&$settings, $conf) {
  $settings['customConfig'] = '/' . drupal_get_path('module', 'eige_ckeditor') . '/eige.ckeditor.config.js';
  $settings['stylesCombo_stylesSet'] = 'drupal:/' . drupal_get_path('module', 'eige_ckeditor') . '/eige.ckeditor.styles.js';
  $settings['contentsCss'][] =  '/' . drupal_get_path('module', 'eige_ckeditor') . '/eige.ckeditor.content.css';
}

?>