<?php

/**
 * Implements hook_node_presave().
 */

function eige_newsletter_content_node_presave($node) {
  if ($node->type == 'simplenews') {
    global $base_url;
    $current_date = date('d/m/Y');
    $node->body['en'][0]['value'] = '<img class="logo" src="'.$base_url.'/sites/all/themes/eigefoundationtheme/logo.png" alt="EIGE logo" title="EIGE Home">'.
      '<div class="newsletter-date" >'.$current_date.'</div>';
    $node->body['en'][0]['format'] = 'full_html';
    foreach ($node->field_newsletter_content[LANGUAGE_NONE] as $index => $value) {
      $nid = $value['target_id'];
      $RelatedNode = node_load($nid);
      $view = node_view($RelatedNode, 'scs');
      unset($view['#contextual_links']);
      $view['links']['#access'] = FALSE;
      $rendered = drupal_render($view);
      $node->body['en'][0]['value'] .= $rendered;
    }
  }
}

function eige_newsletter_content_form_alter(&$form, $form_state) {
  if ($form['#form_id'] == 'simplenews_node_form' && $form['#node_edit_form'] == TRUE) {
    $form['body']['#access'] = FALSE;
  }
}

function eige_newsletter_content_mail_alter(&$message) {
  if (isset($message['module']) && $message['module'] == 'simplenews') {
    global $base_url;
    $message['body']['body'] .= '<style>'.
      "
      .logo{
        float: left;
        display: block;
        margin: -40px 0 60px 0;
      }
      body{
        margin: 0;
        padding: 0;
      }
      * {
        font-family: Helvetica, Arial, sans-serif;
      }
      a{
        text-decoration: none;
        border-bottom: 1px dotted #000;
        color: #000;
      }
      .logo{
        position: absolute;
        top: 42px;
        left: 60px;
      }
      .htmlmail-simplenews-link a{
        background: #E2AB37;
        text-align: center;
        display: block;
        line-height: 3;
        border: 0;
        font-size: 14px;
      }
      br{
        display: none;
      }
      .newsletter-date{
        position: absolute;
        top: 89px;
        right: 60px;
        background: #0056A5;
        color: #fff;
        line-height: 2.7;
        padding: 0 20px;
      }
      h2{
        font-size: 24px;
        font-weight: normal;
      }

      .htmlmail-simplenews-body.htmlmail-body > h2{
        margin: 60px 60px 0px 0px;
        float: right;
        font-weight: bold;
      }

      .clearfix{
        margin: 60px;
      }
      .node{
        margin: 60px 0;
        clear: both;
      }
      .field-name-title-field{
        font-size: 24px;
      }
      .field-name-body{
        color: #666;
        line-height: 1.4;
      }
      .field-name-body{
        color: #666;
      }
      .newsletter-footer{
        font-size: 12px;
        text-align: center;
        background: #E5E4E0;
        height: 60px;
        margin: 0;
      }
      .newsletter-footer a{
        display: block;
        line-height: 60px;
        border:0;
      }
      .social-links{
        text-align: center;
        font-size: 0;
        background: #E5E4E0;
      }
      .social-link {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat 0 0;
        width: 55px;
        height: 55px;
        text-indent: 100%;
        overflow: hidden;
        white-space: nowrap;
        display: inline-block;
        font-size: 11px;
        margin: 0 0 20px 0;
      }
      .social-link a {
        outline: medium none;
        display: block;
        width: 55px;
        height: 55px;
      }
      .social-link-facebook {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat -55px 0;
      }
      .social-link-twitter {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat -110px 0;
      }
      .social-link-youtube {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat -165px 0;
      }
      .social-link-small {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat 0 0;
        width: 32px;
        height: 32px;
        text-indent: 100%;
        overflow: hidden;
        white-space: nowrap;
        float: left;
      }
      .social-link-small a {
        outline: medium none;
        display: block;
        width: 32px;
        height: 32px;
      }
      .social-link-facebook-small {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat 0 0;
      }
      .social-link-twitter-small {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat -32px 0;
      }
      .social-link-youtube-small {
        background: url('".$base_url."/sites/all/themes/eigefoundationtheme/images/social-big-sprite.png') no-repeat -64px 0;
      }
      ".
      '</style>';
  }
}